// packages/react/src/controller.tsx
import { useRouterState } from "@tanstack/react-router";
import { _controller } from "@thcjs/core";
import { HeadRender } from "./render.js";

export function HeadController() {
  const routes = useRouterState({ select: (s) => s.matches });
  const result = _controller("React", routes);
  return <HeadRender head={result.head} />;
}

// packages/solid/src/controller.tsx
import { useRouterState } from "@tanstack/solid-router";
import { _controller } from "@thcjs/core";
import { createComponent } from "solid-js";
import { HeadRender } from "./render.js";

export function HeadController() {
  const routes = useRouterState({ select: (s) => s.matches })();
  const result = _controller("Solid", routes);
  return createComponent(HeadRender, { head: result.head });
}
